// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protos/account.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Accounting {
  public static partial class AccountInfo
  {
    static readonly string __ServiceName = "AccountInfo";

    static readonly grpc::Marshaller<global::Accounting.AccountRequest> __Marshaller_AccountRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Accounting.AccountRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Accounting.Info> __Marshaller_Info = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Accounting.Info.Parser.ParseFrom);

    static readonly grpc::Method<global::Accounting.AccountRequest, global::Accounting.Info> __Method_GetAccountInfo = new grpc::Method<global::Accounting.AccountRequest, global::Accounting.Info>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetAccountInfo",
        __Marshaller_AccountRequest,
        __Marshaller_Info);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Accounting.AccountReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of AccountInfo</summary>
    [grpc::BindServiceMethod(typeof(AccountInfo), "BindService")]
    public abstract partial class AccountInfoBase
    {
      public virtual global::System.Threading.Tasks.Task GetAccountInfo(global::Accounting.AccountRequest request, grpc::IServerStreamWriter<global::Accounting.Info> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for AccountInfo</summary>
    public partial class AccountInfoClient : grpc::ClientBase<AccountInfoClient>
    {
      /// <summary>Creates a new client for AccountInfo</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public AccountInfoClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for AccountInfo that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public AccountInfoClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected AccountInfoClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected AccountInfoClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::Accounting.Info> GetAccountInfo(global::Accounting.AccountRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAccountInfo(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Accounting.Info> GetAccountInfo(global::Accounting.AccountRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetAccountInfo, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override AccountInfoClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AccountInfoClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(AccountInfoBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetAccountInfo, serviceImpl.GetAccountInfo).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, AccountInfoBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetAccountInfo, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Accounting.AccountRequest, global::Accounting.Info>(serviceImpl.GetAccountInfo));
    }

  }
}
#endregion
